// hexa_sai.js - Hexa SAI Self-Improvement Harness (Real LLM)

let hexaChart;
let hexaData = [];
let hexaLabels = [];
let hexaIterationCount = 0;

const HexaWeights = [
    { id: 'w_dev', label: 'Developer Rigidity', value: 75 },
    { id: 'w_crit', label: 'Critic Threshold', value: 60 },
    { id: 'w_temp', label: 'System Temperature', value: 40 },
    { id: 'w_seo', label: 'SEO Aggressiveness', value: 85 }
];

window.initHexaSAI = function() {
    renderWeights();
    initChart();
};

function renderWeights() {
    const list = document.getElementById('hexasai-weights');
    if(!list) return;
    list.innerHTML = '';

    HexaWeights.forEach(w => {
        const item = document.createElement('div');
        item.className = 'weight-item';
        item.innerHTML = `
            <label><span>${w.label}</span> <span><span id="val-${w.id}">${w.value}</span>%</span></label>
            <div class="weight-bar">
                <div class="weight-fill" id="fill-${w.id}" style="width: ${w.value}%;"></div>
            </div>
        `;
        list.appendChild(item);
    });
}

function initChart() {
    const ctx = document.getElementById('hexa-chart');
    if(!ctx || hexaChart) return;

    hexaData = [];
    hexaLabels = [];

    hexaChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: hexaLabels,
            datasets: [{
                label: 'Harness Loss / Error Rate',
                data: hexaData,
                borderColor: '#39FF14',
                backgroundColor: 'rgba(57, 255, 20, 0.1)',
                tension: 0.4,
                fill: true
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                y: {
                    grid: { color: 'rgba(255,255,255,0.05)' },
                    ticks: { color: '#A1A1AA' }
                },
                x: {
                    grid: { color: 'rgba(255,255,255,0.05)' },
                    ticks: { color: '#A1A1AA' }
                }
            },
            plugins: {
                legend: { labels: { color: '#FFFFFF' } }
            }
        }
    });
}

// Called after a build completes in agents.js
window.triggerHexaCycle = async function(originalPrompt, generatedCode) {
    if(!hexaChart) {
        // Init chart if user hasn't visited the tab yet
        const ctx = document.getElementById('hexa-chart');
        if(ctx) initChart();
    }
    
    hexaIterationCount++;

    if(window.logToTerminal) {
        window.logToTerminal(`[Iter ${hexaIterationCount}] Analyzing Builder V2 output quality...`, 'HexaSAI');
    }

    try {
        // Ask Gemini to evaluate the generated code
        const evaluationPrompt = `You are the Hexa SAI Quality Critic. You have just received code generated by an AI agent. Evaluate its quality.

Original User Request: "${originalPrompt ? originalPrompt.substring(0, 500) : 'N/A'}"

Generated Code (first 2000 chars):
${generatedCode ? generatedCode.substring(0, 2000) : 'N/A'}

Score the output and suggest parameter mutations for the harness.`;

        const evalSchema = {
            type: "OBJECT",
            properties: {
                loss_score: { type: "NUMBER", description: "A loss/error score between 0.0 (perfect) and 5.0 (terrible)" },
                code_quality: { type: "STRING", enum: ["Excellent", "Good", "Acceptable", "Poor"], description: "Overall code quality" },
                developer_rigidity_delta: { type: "INTEGER", description: "Change to Developer Rigidity weight, between -10 and +10" },
                critic_threshold_delta: { type: "INTEGER", description: "Change to Critic Threshold weight, between -10 and +10" },
                temperature_delta: { type: "INTEGER", description: "Change to System Temperature weight, between -10 and +10" },
                seo_aggressiveness_delta: { type: "INTEGER", description: "Change to SEO Aggressiveness weight, between -10 and +10" },
                reasoning: { type: "STRING", description: "One sentence explaining the mutations" }
            },
            required: ["loss_score", "code_quality", "developer_rigidity_delta", "critic_threshold_delta", "temperature_delta", "seo_aggressiveness_delta", "reasoning"]
        };

        const evaluation = await window.LLMEngine.generateContent(evaluationPrompt, null, evalSchema);

        // Apply weight mutations
        const deltas = {
            'w_dev': evaluation.developer_rigidity_delta,
            'w_crit': evaluation.critic_threshold_delta,
            'w_temp': evaluation.temperature_delta,
            'w_seo': evaluation.seo_aggressiveness_delta
        };

        HexaWeights.forEach(w => {
            const delta = deltas[w.id] || 0;
            w.value = Math.max(5, Math.min(100, Math.round(w.value + delta)));
            
            const fill = document.getElementById(`fill-${w.id}`);
            const text = document.getElementById(`val-${w.id}`);
            if(fill) fill.style.width = `${w.value}%`;
            if(text) text.innerText = w.value;
        });

        // Update Chart
        hexaLabels.push(`Iter ${hexaIterationCount}`);
        hexaData.push(evaluation.loss_score);
        
        if(hexaData.length > 15) {
            hexaData.shift();
            hexaLabels.shift();
        }
        
        if(hexaChart) hexaChart.update();

        // Log
        if(window.logToTerminal) {
            window.logToTerminal(`Loss: ${evaluation.loss_score.toFixed(3)} | Quality: ${evaluation.code_quality}`, 'HexaSAI');
            window.logToTerminal(`Mutation: ${evaluation.reasoning}`, 'HexaSAI');
        }

    } catch(err) {
        // Fallback: if API fails, still log something useful
        if(window.logToTerminal) {
            window.logToTerminal(`Hexa evaluation skipped (API error): ${err.message}`, 'HexaSAI');
        }
    }
};
